<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=7">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="keywords" content="">
  <meta name="description" content="">

  <title>KESATRIA HARIMAU PUTIH INDONESIA</title>
  <link rel="stylesheet" href="css/style.css">
  <link rel="shortcut icon" href="img/logo2.png" type="image/x-icon">

  <!-- font awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"
    integrity="sha512-RXf+QSDCUQs5uwRKaDoXt55jygZZm2V++WUZduaU/Ui/9EGp3f/2KZVahFZBKGH0s774sd3HmrhUy+SgOFQLVQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>


  <!-- boot -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
    crossorigin="anonymous"></script>


  <!-- lightslider -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightslider/1.1.6/css/lightslider.css"
    integrity="sha512-+1GzNJIJQ0SwHimHEEDQ0jbyQuglxEdmQmKsu8KI7QkMPAnyDrL9TAnVyLPEttcTxlnLVzaQgxv2FpLCLtli0A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  <script src="https://cdnjs.cloudflare.com/ajax/libs/lightslider/1.1.6/js/lightslider.min.js"
    integrity="sha512-Gfrxsz93rxFuB7KSYlln3wFqBaXUc1jtt3dGCp+2jTb563qYvnUBM/GP2ZUtRC27STN/zUamFtVFAIsRFoT6/w=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<style>
  @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&family=Viga&display=swap");
  @import url("https://fonts.googleapis.com/css2?family=PT+Serif:wght@400;700&display=swap");

  *,
  *::before,
  *::after {
    font-family: 'Poppins', sans-serif;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
  }

  body {
    position: relative;
  }

  .navbar {
    align-items: center;
    background-color: transparent;
  }

  .navbar .hamburger span {
    color: #c81c1c;
  }

  .navbar .navbar-brand {
    display: flex;
    align-items: center;
  }

  .navbar .navbar-brand img {
    width: 45px;
    height: 45px;
    transform: translateY(-5px);
  }

  .navbar .navbar-brand h1 {
    font-size: 1.2rem;
    margin-left: 10px;
    font-family: 'Viga', sans-serif;
    text-transform: uppercase;
    font-weight: 800;
    color: #fff;
  }

  .navbar .navbar-collapse .navbar-nav .nav-item .nav-link {
    font-size: 1.1rem;
    margin-left: 20px;
    font-weight: 600;
    color: #fff;
  }

  .navbar .form-inline .form-control {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
  }

  .navbar .form-inline .btn {
    width: 70px;
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
  }

  .navbarKu {
    background-color: #fff;
    box-shadow: 2px 2px 10px 0 rgba(0, 0, 0, 0.3);
  }

  .navbarKu .navbar-brand h1,
  .navbarKu .navbar-collapse .navbar-nav .nav-item .nav-link {
    color: #000;
  }

  .nav-item {
    position: relative;
  }

  .nav-item .dropdown-menu {
    position: absolute;
    left: 0;
  }

  .slideshow {
    position: relative;
    width: 100%;
    max-width: 100%;
    height: auto;
    overflow: hidden;
  }

  .slideshow img {
    width: 100%;
    height: auto;
    vertical-align: middle;
  }

  .mainText {
    position: absolute;
    bottom: 20px;
    /* Sesuaikan jarak dari bawah */
    left: 20px;
    /* Sesuaikan jarak dari kiri */
    color: black;
    text-align: left;
    width: 90%;
    /* Sesuaikan lebar sesuai kebutuhan */
    padding: 15px;
    /* Padding untuk memberikan ruang di sekitar teks */
    border-radius: 10px;
    /* Sudut lengkung pada border */
    z-index: 1;
    /* Untuk mengontrol tumpukan elemen */
  }

  .mainText h3,
  .mainText h1 {
    margin: 0;
    font-size: 18px;
    /* Sesuaikan ukuran font */
  }

  .slideshow .container {
    position: absolute;
    bottom: 150px;
    left: 150px;
  }

  .slideshow .container .mainText {
    position: relative;
  }

  .slideshow .container .mainText .garis {
    position: absolute;
    width: 7px;
    height: 80px;
    border-radius: 10px;
    background-color: #FFA51C;
  }

  .slideshow .container .mainText h3 {
    font-size: 1.5rem;
    font-style: italic;
    margin-left: 30px;
    color: #fff;
  }

  .slideshow .container .mainText h1 {
    margin: 20px 0 40px 30px;
    font-weight: 1000;
    line-height: 10px;
    text-transform: uppercase;
    color: #fff;
  }

  .slideshow .container h3 {
    color: #fff;
    font-size: 1.1rem;
  }


  .title {
    margin: 150px auto 30px auto;
  }

  .title h1 {
    font-size: 2.5rem;
    font-weight: 600;
    text-transform: uppercase;
    text-align: center;
    line-height: 20px;
  }

  .title h2 {
    font-size: 2rem;
    font-weight: 600;
    text-transform: uppercase;
    line-height: 25px;
    text-align: center;
  }

  .title p {
    font-size: 1.1rem;
    text-align: center;
  }

  .perGaleri {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-wrap: wrap;
  }

  .perGaleri img {
    width: 250px;
    height: 150px;
    margin: 5px;
  }

  .scroll {
    background-color: #fff;
    box-shadow: 2px 2px 10px 0 rgba(0, 0, 0, 0.3);
    transition: background-color .5s;
  }

  .scroll .navbar-brand h1,
  .scroll .navbar-collapse .navbar-nav .nav-item .nav-link {
    color: #000;
  }
  

  .sambutan {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    text-align: center;
    padding: 30px 0;
  }

  .sambutan h1 {
    font-size: 2.3rem;
    text-transform: uppercase;
    font-weight: 600;
  }

  .sambutan p {
    font-style: italic;
    font-size: 1rem;
  }

  .kepsek {
    background-image: url("../images/bg-visimisi.png");
    margin: 30px 0;
  }

  .kepsek .container {
    display: flex;
  }

  .kepsek .container img {
    width: 300px;
    height: 300px;
    border-radius: 10px;
    box-shadow: 2px 2px 20px 0 rgba(0, 0, 0, 0.2);
  }

  .kepsek .container .visiMisi {
    display: flex;
    justify-content: space-between;
  }

  .kepsek .container .visiMisi .visi {
    margin: 0 50px 0 100px;
  }

  .kepsek .container .visiMisi .visi h5 {
    font-size: 1.2rem;
    font-style: italic;
  }

  .kepsek .container .visiMisi .visi h3 {
    font-size: 1.5rem;
    font-weight: 300;
    letter-spacing: 2px;
  }

  .kepsek .container .visiMisi .misi h5 {
    font-size: 1.2rem;
    font-style: italic;
  }

  .kepsek .container .visiMisi .misi p {
    font-size: 1.2rem;
    font-family: 'PT Serif', sans-serif;
  }

  .titleArtikel {
    padding: 130px 0 20px 0;
  }

  .titleArtikel h1 {
    text-transform: uppercase;
    font-size: 1.5rem;
    letter-spacing: 0px;
    font-weight: 600;
  }

  .artikel .perArtikel {
    display: flex;
    margin-bottom: 10px;
  }

  .artikel .perArtikel:hover h3 {
    color: #0e85e7;
    transition: .5s;
  }

  .artikel .perArtikel img {
    width: 250px;
    height: 150px;
    margin-right: 20px;
    border-radius: 10px;
  }

  .artikel .perArtikel h3 {
    font-size: 1.7rem;
    font-weight: 600;
    color: #000;
    line-height: 30px;
  }

  .artikel .perArtikel p {
    color: #000;
  }

  .iconBox {
    position: fixed;
    right: 0;
    top: 50%;
    transform: translate(0, -50%);
    z-index: 9999999999999999999999999999999999999999999;
  }

  .iconBox .perIconBox {
    width: 50px;
    height: 45px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: #fff;
  }

  .perIconBox:hover {
    color: #dadada;
  }

  .wa {
    background-color: #1bc22e;
  }

  .fb {
    background-color: #4867AA;
  }

  .ig {
    background: linear-gradient(to bottom left, #5056C5, #EE4B51, #F7B04D);
  }

  .yt {
    background-color: #FF0000;
  }

  .linkin {
    background-color: #0077B5;
  }

  /* CSS untuk tampilan mobile */
  @media (max-width: 768px) {
    .mainText {
      bottom: 100px;
      /* Sesuaikan jarak dari bawah */
      left: 10px;
      /* Sesuaikan jarak dari kiri */
      width: 80%;
      /* Sesuaikan lebar sesuai kebutuhan */
    }
    

    .mainText h3 {
      font-size: 16px;
      /* Sesuaikan ukuran font */
    }

    .mainText h1 {
      font-size: 22px;
      margin-bottom: 3px;
    }

    @media (max-width: 1175px) {
      .jurusan .boxJurusan .perBox {
        width: 375px;
        height: 225px;
      }
    }

    @media (max-width: 1000px) {

      .shareArtikel img,
      .penulis img {
        width: 80%;
      }

      .detailArtikel h2 {
        font-size: 2rem;
      }

      .kepsek .container img {
        margin-right: 30px;
      }

      .kepsek .container .visiMisi {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-pack: inherit;
        -ms-flex-pack: inherit;
        justify-content: inherit;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
      }

      .kepsek .container .visiMisi .visi {
        margin: 0 0 20px 0;
      }

      .kepsek .container .visiMisi .visi h3 {
        font-weight: 600;
      }

      .kepsek .container .visiMisi .misi p {
        font-size: 1rem;
      }

      .sambutan h1 {
        font-size: 1.7rem;
      }

      .sambutan p {
        font-size: .8rem;
      }

      .perGaleri img {
        width: 200px;
        height: 100px;
      }

      .title h2 {
        font-size: 1.7rem;
      }

      .jurusan .boxJurusan .perBox {
        width: 300px;
        height: 200px;
      }
    }

    @media (max-width: 995px) {
      .artikel .perArtikel h3 {
        font-size: 1.5rem;
      }

      .artikel .perArtikel p {
        font-size: .9rem;
      }

      .containerArtikelHome .artikelHome .perArtikelHome {
        width: 300px;
      }

      .containerArtikelHome .artikelHome .perArtikelHome img {
        height: 200px;
      }

      .containerEkstra {
        height: 50vh;
      }

      .footerContactUs .perFooterContactUs p {
        font-size: .7rem;
      }
    }

    @media (max-width: 770px) {
      .jurusan h2 {
        font-size: 2rem;
      }

      .jurusan .boxJurusan .perBox {
        width: 80%;
        height: 250px;
      }

      .containerArtikelHome .artikelHome .perArtikelHome {
        width: 100%;
      }

      .containerArtikelHome .artikelHome .perArtikelHome img {
        height: 300px;
      }

      .artikel .perArtikel {
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
      }

      .artikel .perArtikel img {
        width: 100%;
        height: 250px;
        margin-right: 0;
        margin-bottom: 10px;
      }

      .artikel .perArtikel .textArtikel h3 {
        font-size: 1.7rem;
      }

      .kepsek .container {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        text-align: center;
      }

      .kepsek .container img {
        margin-right: 0;
        margin-bottom: 20px;
      }

      .sambutan h1 {
        font-size: 1.5rem;
      }

      .pembinaEkstrakulikuler .perPembina {
        width: 80%;
        height: 300px;
      }
    }

    @media (max-width: 767px) {
      .footerContactUs .perFooterContactUs p {
        font-size: 1rem;
      }

      .shareArtikel img,
      .penulis img {
        width: 50%;
      }
    }

    @media (max-width: 650px) {
      .slideshow .container {
        left: 0;
        bottom: 250px;
      }

      .imgArtikel {
        height: 400px;
      }

      .detailArtikel h2 {
        font-size: 1.7rem;
      }
    }

    @media (max-width: 475px) {
      .perGaleri img {
        width: 150px;
        height: 100px;
      }

      .pembinaEkstrakulikuler .perPembina {
        width: 100%;
        height: 300px;
      }

      .containerArtikelHome h2 {
        font-size: 1.5rem;
      }

      .containerArtikelHome .artikelHome .perArtikelHome {
        width: 100%;
      }

      .containerArtikelHome .artikelHome .perArtikelHome img {
        height: 250px;
      }

      .title h1 {
        font-size: 1.7rem;
      }

      .title p {
        font-size: 1rem;
      }
    }

    @media (max-width: 450px) {

      .shareArtikel img,
      .penulis img {
        width: 80%;
        height: 250px;
      }

      .imgArtikel {
        height: 200px;
      }

      .navbar .navbar-brand img {
        width: 33px;
        height: 33px;
      }

      .navbar .navbar-brand h1 {
        font-size: 1rem;
      }

      .containerEkstra {
        margin-top: 60px;
      }

      .slideshow .container .mainText .garis {
        height: 70px;
      }

      .slideshow .container .mainText h3 {
        font-size: 1.2rem;
        margin-left: 20px;
      }

      .slideshow .container .mainText h1 {
        margin: 20px 0 30px 20px;
        font-size: 1.8rem;
      }

      .slideshow .container h3 {
        font-size: .9rem;
      }

      .artikel .perArtikel img {
        height: 200px;
      }

      .artikel .perArtikel .textArtikel h3 {
        font-size: 1.5rem;
      }

      .artikel .perArtikel .textArtikel p {
        font-size: .8rem;
      }

      .artikelPagination span {
        padding: 5px 15px;
        font-size: .9rem;
        border: 1px solid #000;
        margin: 0 5px;
      }

      .titleArtikel h1 {
        text-align: center;
      }

      .artikel .perArtikel img {
        height: 200px;
      }

      .artikel .perArtikel .textArtikel h3 {
        font-size: 1.5rem;
      }

      .artikel .perArtikel .textArtikel p {
        font-size: .8rem;
      }

      .artikelPagination span {
        padding: 3px 10px;
        font-size: .7rem;
      }

      .jurusan h2 {
        font-size: 1.5rem;
      }

      .jurusan .boxJurusan .perBox {
        width: 100%;
      }

      .jurusan .boxJurusan .perBox h3 {
        font-size: .8rem;
      }

      .iconBox {
        top: 100%;
        -webkit-transform: translate(0, -100%);
        transform: translate(0, -100%);
        width: 100%;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
      }

      .iconBox .perIconBox {
        width: 300px;
        border-bottom: 0px solid #0306aa;
        border-right: 0px solid #666666;
      }

      .pembinaEkstrakulikuler .perPembina {
        height: 200px;
      }
    }

    @media (max-width: 375px) {
      .sambutan h1 {
        font-size: 1.2rem;
      }

      .sambutan p {
        font-size: .7rem;
      }

      .kepsek .container img {
        width: 200px;
        height: 200px;
      }

      .kepsek .container .visiMisi .visi h5 {
        font-size: .9rem;
      }

      .kepsek .container .visiMisi .visi h3 {
        font-size: 1rem;
      }

      .kepsek .container .visiMisi .misi h5 {
        font-size: .9rem;
      }

      .kepsek .container .visiMisi .misi p {
        font-size: .9rem;
      }

      .perGaleri img {
        width: 100%;
        height: 200px;
      }

      .perFooterContactUs p {
        font-size: .9em;
      }
    }

    /* Media query untuk tata letak pada mobile */
    @media (max-width: 768px) {
      .footer-content {
        flex-direction: column;
        /* Mengubah tata letak teks dan ikon menjadi satu kolom */
        align-items: center;
        /* Pusatkan secara horizontal */
        text-align: center;
        /* Pusatkan teks ke tengah */
      }

      .iconBox {
        margin-top: 10px;
        /* Berikan margin atas pada ikon untuk memisahkan dengan teks */
      }
    }

  }
</style>

<body>
  <nav class="navbar navbar-expand-lg navbar-light  navbarHome fixed-top">
    <div class="container">

      <a class="navbar-brand" href="#">
        <img src="img/logo2.png" alt="Logo kharpi">
        <h1>KESATRIA HARIMAU<br>PUTIH INDONESIA</h1>
      </a>

      <button class="navbar-toggler hamburger" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="dashboard.php">Home</a>
            </li>

            <li class="nav-item active">
              <a class="nav-link" href="portalberita/index.php">Artikel</a>
            </li>

            <li class="nav-item active">
              <a href="#" class="nav-link dropdown-toggle" id="dropdownMenuLink" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                More
              </a>

           <li class="nav-item active">
              <a class="nav-link" href="login.php">Login</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">

            <input class="form-control sm-2" type="search" placeholder="Cari Artikel" aria-label="Search">

            <button class="btn btn-primary sm-0" type="submit">
              <i class="fas fa-search"></i>
            </button>

          </form>
        </div>

      </div>
    </nav>



  <ul id="autoWidth" class="cs-hidden">
    <li class="item-a">
      <section class="slideshow">
        <img class="satu" src="img/kharpi1.jpg" alt="Team Work">
        <div class="shadow"></div>
        <div class="container">
          <div class="mainText">
            <div class="garis"></div>
            <h3 style="color: black; font-size: 18px;">PENCAK SILAT</h3>
            <h1 style="color: black; font-size: 24px; margin-bottom: 5px;">Kesatria</h1>
            <h1 style="color: black; font-size: 24px; margin-bottom: 0;">Harimau Putih Indonesia</h1>
          </div>
        </div>
      </section>
    </li>
  </ul>
  </ul>
  <div class="sambutan">
    <h2>PS. KESATRIA HARIMAU PUTIH INDONESIA</h2>
    <p>
      Kesatria Harimau Putih Indonesia Sebagai
      salah satu perguruan yang dibentuk untuk <br>
      meneruskan/melestarikan Keilmuan pencak
      silat yang ada di Indonesia
    </p>
  </div>


  <div class="kepsek">
    <div class="container">
      <img src="img/ketua.jpg" alt="Ketua kharpi">

      <div class="visiMisi">

        <div class="visi">
          <h5>Our Vision</h5>
          <h3>Melestarikan keilmuan pencak silat Indonesia melalui perguruan Kesatria Harimau Putih Indonesia."</h3>
        </div>

        <div class="misi">
          <h5>Sejarah Kesatria Harimau Putih Indonesia </h5>
          <p>
            Pendiri Pencak
            Silat Kesatria Harimau Putih adalah Bapak
            Halim Mubarroq yang merupakan putra dari
            Bapak Zainal Arifin, dimana Bapak Zainal
            Arifin adalah murid Bapak Jaeni yang
            merupakan guru Cimande di Banten. Dan
            Bapak Zainal Arifin juga murid dari Guru
            Daeng Massa seorang pendekar di Mandar
            Sulawesi Selatan. Halim Mubarroq juga
            pernah belajar silat dengan Bapak Awang
            Suwanda yang merupakan murid langsung
            Bapak Moch. Hadimulyo pendiri perguruan
            pencak Silat KPS Nusantara. Halim Mubarroq
            yang mendirikan perguruan silat Kesatria
            Harimau Putih Indonesia juga di dampingi
            oleh Bapak Junaidi pendekar dari Makassar
            Sulawesi Selatan dan Bapak Abdul Kadar juga
            pendekar dari Makassar Sulawesi Selatan
            dalam mendirikan perguruan ini.
          </p>
        </div>

      </div>

    </div>
  </div>
  <div class="containerArtikelHome container">
    <h2>Artikel Terbaru</h2>

    <div class="artikelHome">

<a class="perArtikelHome" href="portalberita/detail.php?id=11&judul=sejarah-kesatria-harimau-putih-indonesia">
    <div style="text-align: center;">
        <img src="img/logo2.png" alt="Foto Artikel" style="display: block; margin: auto; width: 200px; height: auto;">
    </div>
    <h3>Arti Lambang/Logo</h3>
    <small>Di tulis oleh : <span>Halim Mubarroq </span></small>
    <p>
        Makna arti kata Kesatria : Melambangkan
        seseorang yang menghargai, mengabdi,
        menjunjung tinggi pada penegakan hukum,
        kebenaran dan keadilan.
    </p>
</a>

      <a class="perArtikelHome" href="portalberita/detail.php?id=12&judul=panca-prasetya-dan-uraiannya-panca-prasetya-kesatria-harimau-putih-indonesia-:">
            <div style="text-align: center;">
                <img src="img/logo2.png" alt="Foto Artikel" style="display: block; margin: auto; width: 200px; height: auto;">
            </div>
            <h3>Panca Prasetya Kesatria Harimau Putih Indonesia :</h3>
            <small>Di tulis oleh : <span>Halim Mubarroq </span></small>
            <p>
                Panca Prasetya Kesatria Harimau Putih Indonesia :
            </p>
        </a>

        <a class="perArtikelHome" href="halaman-artikel-2.html">
            <div style="text-align: center;">
                <img src="img/logo2.png" alt="Foto Artikel" style="display: block; margin: auto; width: 200px; height: auto;">
            </div>
            <h3>Penjabaran Janji Panca Prasetya Kesatria Harimau Putih Indonesia :</h3>
            <small>Di tulis oleh : <span>Halim Mubarroq</span></small>
            <p>
                Penjabaran dari Janji Panca Prasetya Kesatria Harimau Putih Indonesia :
            </p>
        </a>

        <a class="perArtikelHome" href="portalberita/detail.php?id=13&judul=mars-kesatria-harpi">
            <div style="text-align: center;">
                <img src="img/logo2.png" alt="Foto Artikel" style="display: block; margin: auto; width: 200px; height: auto;">
            </div>
            <h3>Mars Kesatria HARPI</h3>
            <small>Di tulis oleh : <span>Halim Mubarroq</span></small>
            <p>
                Mars Kesatria Harimau Putih Indonesia, Berikut Marsnya
            </p>
        </a>

        <a class="perArtikelHome" href="halaman-artikel-4.html">
            <div style="text-align: center;">
                <img src="img/logo2.png" alt="Foto Artikel" style="display: block; margin: auto; width: 200px; height: auto;">
            </div>
            <h3>ARTI HORMAT PERGURUAN</h3>
            <small>Di tulis oleh : <span>Halim Mubarroq</span></small>
            <p>
                Berikut ini merupakan arti hormat perguruan kesatria harimau putih indonesia
            </p>
        </a>

        <a class="perArtikelHome" href="halaman-artikel-5.html">
            <div style="text-align: center;">
                <img src="img/logo2.png" alt="Foto Artikel" style="display: block; margin: auto; width: 200px; height: auto;">
            </div>
            <h3>TINGKATAN SABUK DAN MAKNA WARNA SABUK</h3>
            <small>Di tulis oleh : <span>Halim Mubarroq</span></small>
            <p>
                Berikut ini merupakan tingkatan sabuk dan makna warna perguruan kesatria harimau putih indonesia
            </p>
        </a>
    </div>
</div>
  <!-- sosmed icon -->
  <div class="iconBox">
    <a href="" class="perIconBox wa">
      <i class="fab fa-whatsapp"></i>
    </a>

    <a href="" class="perIconBox fb">
      <i class="fab fa-facebook-f"></i>
    </a>

    <a href="" class="perIconBox ig">
      <i class="fab fa-instagram"></i>
    </a>

    <a href="" class="perIconBox yt">
      <i class="fab fa-youtube"></i>
    </a>

    <a href="" class="perIconBox linkin">
      <i class="fab fa-linkedin-in"></i>
    </a>
  </div>

  <div class="footer">

    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h4 class="my-4 text-white text-center">Contact Us</h4>

          <div class="footerContactUs">

            <div class="perFooterContactUs">
              <i class="fas text-white fa-envelope"></i>
              <p class="text-white">kharpi.gor@gmail.com</p>
            </div>

            <div class="perFooterContactUs">
              <i class="fas text-white fa-phone-alt"></i>
              <p class="text-white">085778830331</p>
            </div>

            <div class="perFooterContactUs">
              <i class="fas text-white fa-road"></i>
              <p class="text-white">Jl.Cemara III ujung, Kp.Cikunir Bulak No.160, RT.04/RW.03/RW, Jaka Mulya</p>
            </div>

          </div>

        </div>
        <div class="col-md-4">
          <h4 class="my-4 text-center text-white">About</h4>
          <div class="footerAbout">
            <a href="" class="text-white">Artikel</a>
            <a href="" class="text-white">Galeri</a>
            <a href="" class="text-white">Contact Us</a>
            <a href="" class="text-white">Kesatria</a>
          </div>
        </div>


        <div class="col-md-4 text-center">
          <h4 class="my-4 text-white">Newsletter</h4>
          <form>

            <div class="form-group">
              <input class="form-control" type="search" placeholder="Example@gmail.com" aria-label="Search">
              <button class="btn btn-primary btn-newsletter" type="submit">Kirim</button>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="footerCopyright">
    <p class="text-white">
      <i class="far fa-copyright"></i>2024 By : <span>Fajar</span> & Kesatria Harimau Putih Indonesia <a href="">
        Jakarta</a>
    </p>
  </div>
  <script src="js/script.js"></script>
</body>

</html>